# Generated by Django 3.0.7 on 2020-06-11 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='amoung',
            new_name='amount',
        ),
    ]
